web:
  build: .
  ports:
    - '3000:3000'
  working_dir: /usr/src/app
  volumes:
    - ./:/usr/src/app
  links:
     - mysql

mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=phonebook
      - MYSQL_USER=phonebook_user  
      - MYSQL_PASSWORD=123
    ports:
      -  '3307:3306'
